working on cache

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,7 +2,8 @@
 
 ## VARIABLES
 RUN_COMMAND=run_tor
-TOR_SRC_NAME=tor-0.3.0.10.tar.gz
+TOR_VER=0.3.0.10
+TOR_SRC_NAME=tor-${TOR_VER}.tar.gz
 TOR_DIST_URL=https://www.torproject.org/dist/
 
 
@@ -21,58 +22,76 @@ TOR_SIG_NAME=${TOR_SRC_NAME}.asc
 TOR_SRC_URL=${TOR_DIST_URL}${TOR_SRC_NAME}
 TOR_SRC_SIG_URL=${TOR_DIST_URL}${TOR_SIG_NAME}
 
-
+################################################################################
+# Try use cache
+################################################################################
+mkdir -p $CACHE_DIR
+grep -wq "${TOR_SRC_NAME}" $CACHE_DIR/tor_version.txt
+if [ $? -eq 0 ] ; then # Reusing cache
+   TOR_IS_CACHED=1
+else
+   TOR_IS_CACHED=0
+fi
 
 ################################################################################
 # GET SOURCES
 ################################################################################
-echo "Downloading ${TOR_SRC_URL}"
-wget -q $TOR_SRC_URL
+if [ $TOR_IS_CACHED -eq 0 ] ; then
+    echo "Downloading ${TOR_SRC_URL}"
+    wget -q $TOR_SRC_URL
 
-if [ $? - ne 0]; then
-    echo "FAILED to obtain ${TOR_SRC_URL}" | indent
-    exit 1
+    if [ $? - ne 0]; then
+        echo "FAILED to obtain ${TOR_SRC_URL}" | indent
+        exit 1
+    fi
+
+    echo "Downloading ${TOR_SRC_SIG_URL}"
+    wget -q $TOR_SRC_SIG_URL
+
+    if [ $? -ne 0 ]; then
+        echo "FAILED to obtain signature ${TOR_SRC_SIG_URL}" | indent
+        exit 1
+    fi
 fi
-
-echo "Downloading ${TOR_SRC_SIG_URL}"
-wget -q $TOR_SRC_SIG_URL
-
-if [ $? -ne 0 ]; then
-    echo "FAILED to obtain signature ${TOR_SRC_SIG_URL}" | indent
-    exit 1
-fi
-
 ################################################################################
 # VERIFY INTEGRITY
 ################################################################################
-
-gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290
-gpg --keyserver pool.sks-keyservers.net --recv-keys 0x6AFEE6D49E92B601
-gpg --verify ${TOR_SIG_NAME} ${TOR_SRC_NAME} | grep -c "Good signature"
-if [ $? -lt 1 ]; then
-    echo "FAILED to verify the signature" | indent
-    exit 1
+if [ $TOR_IS_CACHED -eq 0 ] ; then
+    gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290
+    gpg --keyserver pool.sks-keyservers.net --recv-keys 0x6AFEE6D49E92B601
+    gpg --verify ${TOR_SIG_NAME} ${TOR_SRC_NAME} | grep -c "Good signature"
+    if [ $? -lt 1 ]; then
+        echo "FAILED to verify the signature" | indent
+        exit 1
+    fi
 fi
-
 ################################################################################
-# COMPILE & INSTALL
+# COMPILE
+################################################################################
+if [ $TOR_IS_CACHED -eq 0 ] ; then
+    tar -zxf ${TOR_SRC_NAME}
+    cd tor-${TOR_VER}
+    ./configure --prefix=$CACHE_DIR/tor
+    if [ $? -ne 0 ]; then
+        echo "FAILED to configure for compliation" | indent
+        exit 1
+    fi
+
+    make install
+    if [ $? -ne 0 ]; then
+        echo "FAILED to run make install" | indent
+        exit  1
+    fi
+fi
+################################################################################
+# INSTALL
 ################################################################################
 
-# Finally do some compilation.
-tar -zxf ${TOR_SRC_NAME}
-cd tor-*
-./configure --prefix=$BUILD_DIR
-if [ $? -ne 0 ]; then
-    echo "FAILED to configure for compliation" | indent
-    exit 1
-fi
+# Cached instalation to real build dir
+cp -r $CACHE_DIR/tor ${BUILD_DIR}
 
-make install
-if [ $? -ne 0 ]; then
-    echo "FAILED to run make install" | indent
-    exit  1
-fi
-
+# Saves the version just compiled
+echo "${TOR_SRC_NAME}" > $CACHE_DIR/tor_version.txt
 
 cat > ${BUILD_DIR}/bin/${RUN_COMMAND} <<EOF
 #!/usr/bin/env bash
@@ -96,3 +115,6 @@ EOF
 chmod a+x ${BUILD_DIR}/bin/${RUN_COMMAND}
 
 echo "Installed Tor successfully" | indent
+
+
+
