0.1.1: Fixed the issues with the scripts

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,9 +6,12 @@
 
 set -x
 
-HEROKU_BUILD_DIR=$1
-HEROKU_CACHE_DIR=$2
-HEROKU_ENV_DIR=$3
+HEROKU_BUILD_DIR="$1"
+HEROKU_CACHE_DIR="$2"
+HEROKU_ENV_DIR="$3"
+
+HEROKU_THIS_DIR=$(dirname "$0")
+HEROKU_PACK_DIR=$(cd "$HEROKU_THIS_DIR"; cd ..; pwd)
 
 # Essental functions
 
@@ -16,10 +19,8 @@ export_env_vars() {
   env_dir=$1
   whitelist_regex=${2:-''}
   blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
-
   if [ -d "$env_dir" ]; then
-    for e in $env_dir; do
-      [[ -e "$e" ]] || break
+    for e in $(ls "$env_dir"); do
       echo "$e" | grep -E "$whitelist_regex" | grep -qvE "$blacklist_regex" &&
       export "$e=$(cat $env_dir/$e)"
       :
@@ -43,11 +44,12 @@ TOR_COMMAND="run_tor_proxy"
 TOR_DIST_URL="https://dist.torproject.org/"
 
 if [ -z "$TOR_VERSION" ]; then
-  TOR_SRC_NAME=tor-${TOR_VERSION}.tar.gz
-else
-  TOR_SRCH="tor-.\..\..\..\.tar\.gz"
-  TOR_SRC_NAME=$(curl -s "$TOR_DIST_URL" | grep -o -e "$TOR_SRCH" | sort | tail -1)
+  TOR_SRCH=".\..\..\..\.tar"
+  TOR_PACKAGE=$(curl -s "$TOR_DIST_URL" | grep -o -e "$TOR_SRCH" | sort | tail -1)
+  TOR_VERSION="${TOR_PACKAGE/.tar/}"
 fi
+
+TOR_SRC_NAME="tor-${TOR_VERSION}.tar.gz"
 
 if [ -z "$TOR_CONTROL_PASS" ]; then
   TOR_CONTROL_PASS="torProxy@123"
@@ -115,7 +117,7 @@ fi
 ################################################################################
 if [ $IS_TOR_CACHED -eq 0 ] ; then
     tar -zxf "$TOR_SRC_NAME"
-    cd "tor-${TOR_VER}" || echo "FAILED to configure Tor"
+    cd "tor-${TOR_VERSION}" || echo "FAILED to configure Tor"
 
     ./configure --prefix="${HEROKU_CACHE_DIR}/tor"
     if [ $? -ne 0 ]; then
@@ -140,6 +142,10 @@ cp -r "${HEROKU_CACHE_DIR}/tor" "$HEROKU_BUILD_DIR"
 # Save the version compiled now
 echo "$TOR_SRC_NAME" > "${HEROKU_CACHE_DIR}/tor_version.txt"
 
+################################################################################
+# Configure Tor
+################################################################################
+
 echo "Configuring the Tor Proxy" | indent
 
 TOR_HASHED_PASS=$("${HEROKU_BUILD_DIR}/tor/bin/tor" --hash-password "$TOR_CONTROL_PASS")
@@ -158,9 +164,17 @@ EOF
 
 chmod a+x "${HEROKU_BUILD_DIR}/tor/bin/${TOR_COMMAND}"
 
+################################################################################
+# Activate Runner
+################################################################################
+
 echo "Activating the auto-runner" | indent
 
-cp "${BUILDPACK_DIR}/extra/${TOR_COMMAND}.sh" "${BUILD_DIR}/.profile.d/"
-chmod +x "${BUILD_DIR}/.profile.d/${TOR_COMMAND}.sh"
+if [ ! -d "${HEROKU_BUILD_DIR}/.profile.d/" ]; then
+  mkdir "${HEROKU_BUILD_DIR}/.profile.d/"
+fi
+
+cp "${HEROKU_PACK_DIR}/extra/${TOR_COMMAND}.sh" "${HEROKU_BUILD_DIR}/.profile.d/"
+chmod +x "${HEROKU_BUILD_DIR}/.profile.d/${TOR_COMMAND}.sh"
 
 echo "SUCCESS at installing Tor Proxy" | indent
